name: Amend
version: '${project.version}'
main: com.tronmc.beta.tronmcupdater.TronMCUpdater
api-version: 1.19
load: STARTUP
description: A plugin that auto updates purpur.
website: https://beta.tronmc.com/projects/amend
